name = "hacc-shortener"
main = "src/index.js"
compatibility_date = "2022-10-22"

kv_namespaces = [
  { binding = "SHORTENER_KV", id = "804a2458995e4088a92a157135bab4a6", preview_id = "4d9369f9c68f48abb3422d396042bd9b" },
]

[vars]
HOST_URL = "https://hacc-shortener.kmal.workers.dev"